Feature/charities - Volunteers and Charities About Pages Added
chingu-voyages/v8-bears-team-06 pull request #86
Opened 2019-04-26 10:29 UTC by willjw3

Fixes #85

2019-04-26 12:53 UTC, hitochan777 requested changes

2019-04-26 12:53 UTC, hitochan777 commented on src/client/pages/volunteers.jsx
> +        // height: 100vh;
delete this if you don't need it

2019-04-26 13:08 UTC, willjw3 commented on src/client/pages/volunteers.jsx
> +        // height: 100vh;
Done.

2019-04-27 09:32 UTC, hitochan777 approved these changes
LGTM!

2019-04-27 09:33 UTC, merged